name: Hola Mundo en GitHub Actions

on:
  workflow_dispatch:  # Ejecutar manualmente

jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Imprimir mensaje en consola
        run: echo "¡Hola Mundo desde GitHub Actions!"

